### ISSUE TITLE
add support to change ADC address

### ISSUE THREAD

**Issue by mnemocron** [andriyadi/ESP32-TLA2024#2]
When testing with a TLA2024 having the adress pin on GND results in an address `1001 000` (`0x72`).
However when I checked on what address the default config bytes are returned I found it to be on address `1100 1000` (`0xC8`).

Also when using multiple ADC chips one needs to use multiple addresses.

**Comment by andriyadi** [comment]
Wow. Thanks guys. I’m currently abroad and have limited bandwidth. Will take a look in 2 days.

**Comment by andriyadi** [comment]
Agreed. Your PR is just merged. Thanks again.
